name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      # Definieer een containeromgeving voor de tests
      testcontainer:
        image: python:3.10
        options: --entrypoint /bin/sh
        volumes:
          - ${{ github.workspace }}:/workspace
        env:
          PYTHONPATH: /workspace

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install pytest
          pip install .

      - name: Run Pytest Unit Tests
        run: |
          pytest ${{ github.workspace }}/utest/utest.robot
      
      - name: Run Robot Framework Tests
        run: |
          robot ${{ github.workspace }}/atest/atest.robot
